const elements = {
  app: document.querySelector(".app"),
  sidebar: document.getElementById("sidebar"),
  menuBtn: document.getElementById("menuBtn"),
  settingsBtn: document.getElementById("settingsBtn"),
  hideSidebarBtn: document.getElementById("hideSidebarBtn"),
  newChatBtn: document.getElementById("newChatBtn"),
  historyList: document.getElementById("historyList"),
  chatMain: document.getElementById("chatMain"),
  chatHistory: document.getElementById("chatHistory"),
  chatForm: document.getElementById("chatForm"),
  promptInput: document.getElementById("promptInput"),
  sendBtn: document.getElementById("sendBtn"),
  modelSelect: document.getElementById("modelSelect"),
  statusText: document.getElementById("statusText"),
  userId: document.getElementById("userId"),
  toast: document.getElementById("toast"),
  settingsModal: document.getElementById("settingsModal"),
  settingsCloseBtn: document.getElementById("settingsCloseBtn"),
  settingsTabs: document.getElementById("settingsTabs"),
  settingsTabModel: document.getElementById("settingsTabModel"),
  settingsTabRoot: document.getElementById("settingsTabRoot"),
  settingsPanelModel: document.getElementById("settingsPanelModel"),
  settingsPanelRoot: document.getElementById("settingsPanelRoot"),
  systemPromptInput: document.getElementById("systemPromptInput"),
  savePromptBtn: document.getElementById("savePromptBtn"),
  logoutBtn: document.getElementById("logoutBtn"),
  settingsForm: document.getElementById("settingsForm"),
  apiBaseUrl: document.getElementById("apiBaseUrl"),
  clearCacheBtn: document.getElementById("clearCacheBtn"),
  backModal: document.getElementById("backModal"),
  backConfirmBtn: document.getElementById("backConfirmBtn"),
  backCancelBtn: document.getElementById("backCancelBtn"),
};

export { elements };
